{ pkgs }:
let
  source = builtins.readFile ../../nixfied/runner/env-sandbox.nix;
  commonSource = builtins.readFile ../../nixfied/runner/common-runtime.nix;
in
assert pkgs.lib.hasInfix "run_in_sandbox_runtime() {" source;
assert pkgs.lib.hasInfix "run_in_sandbox() {" source;
assert pkgs.lib.hasInfix "commonRuntimeShell = import ./common-runtime.nix" source;
assert pkgs.lib.hasInfix "\${commonRuntimeShell}" source;
assert pkgs.lib.hasInfix "ERROR: task runtime.workdir=custom but customWorkdir is empty" source;
assert pkgs.lib.hasInfix "ERROR: unknown runtime.workdir '$workdir_kind'" source;
assert pkgs.lib.hasInfix "env -i" source;
assert pkgs.lib.hasInfix "\"HOME=$home_value\"" source;
assert pkgs.lib.hasInfix "\"TMPDIR=$tmp_value\"" source;
assert pkgs.lib.hasInfix "\"XDG_DATA_HOME=$xdg_data_value\"" source;
assert pkgs.lib.hasInfix "\"XDG_STATE_HOME=$xdg_state_value\"" source;
assert pkgs.lib.hasInfix "\"XDG_CACHE_HOME=$xdg_cache_value\"" source;
assert pkgs.lib.hasInfix "\"REGISTRY_ROOT=$registry_root_value\"" source;
assert pkgs.lib.hasInfix "\"CI_ARTIFACTS_DIR=$artifacts_dir_value\"" source;
assert pkgs.lib.hasInfix "local host_nix_user_conf_files=\"''\${NIX_USER_CONF_FILES:-}\"" source;
assert pkgs.lib.hasInfix "local host_nix_config=\"''\${NIX_CONFIG:-}\"" source;
assert pkgs.lib.hasInfix "local host_nix_ssl_cert_file=\"''\${NIX_SSL_CERT_FILE:-}\"" source;
assert pkgs.lib.hasInfix "env_cmd+=(\"NIX_USER_CONF_FILES=$host_nix_user_conf_files\")" source;
assert pkgs.lib.hasInfix "env_cmd+=(\"NIX_CONFIG=$host_nix_config\")" source;
assert pkgs.lib.hasInfix "env_cmd+=(\"NIX_SSL_CERT_FILE=$host_nix_ssl_cert_file\")" source;
assert pkgs.lib.hasInfix "/usr/bin/xcrun --sdk macosx --show-sdk-path" source;
assert pkgs.lib.hasInfix "env_cmd+=(\"SDKROOT=$host_sdkroot\")" source;
assert pkgs.lib.hasInfix "load_runtime_plan() {" source;
assert pkgs.lib.hasInfix "eval \"$runtime_plan_shell\"" source;
assert pkgs.lib.hasInfix "ENV_SANDBOX_STATIC_RUNTIME_PACKAGES_PATH" source;
assert pkgs.lib.hasInfix "ENV_SANDBOX_STATIC_RUNTIME_PRIMITIVES_TSV" source;
assert pkgs.lib.hasInfix "ENV_SANDBOX_STATIC_RUNTIME_PORTS_TSV" source;
assert pkgs.lib.hasInfix "ENV_SANDBOX_STATIC_SERVICE_NAMES" source;
assert pkgs.lib.hasInfix "env_sandbox_runtime_env_offset() {" source;
assert pkgs.lib.hasInfix "is_reserved_runtime_env_name() {" source;
assert !(pkgs.lib.hasInfix "valid_log_level() {" source);
assert !(pkgs.lib.hasInfix "valid_output_mode() {" source);
assert pkgs.lib.hasInfix ".allowSensitivePassThrough // false" source;
assert pkgs.lib.hasInfix "ERROR: runtime-owned passthrough env blocked name=$pass_name" source;
assert pkgs.lib.hasInfix "ERROR: runtime-owned env override blocked name=$env_name" source;
assert pkgs.lib.hasInfix "ERROR: sensitive passthrough env blocked name=$pass_name" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_DIR_SCOPE_OVERRIDE" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_DIR_BASE" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_DIR_SCOPE" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_HOME" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_TMPDIR" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_XDG_DATA_HOME" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_REGISTRY_ROOT" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_ARTIFACTS_DIR" source;
assert pkgs.lib.hasInfix "NIXFIED_RUNTIME_SERVICE_ROOT" source;
assert pkgs.lib.hasInfix "NIXFIED_EXECUTOR_SELF" source;
assert pkgs.lib.hasInfix "NIXFIED_ORCHESTRATOR_SELF" source;
assert pkgs.lib.hasInfix "NIXFIED_MODEL_FILE" source;
assert pkgs.lib.hasInfix "NIXFIED_RUN_ID" source;
assert pkgs.lib.hasInfix "NIXFIED_PARENT_WORKFLOW_ID" source;
assert pkgs.lib.hasInfix "NIX_BUILD_TOP" source;
assert pkgs.lib.hasInfix "NIXFIED_SERVICE_" source;
assert pkgs.lib.hasInfix "NIXFIED_SERVICE_''\${service_token}_DATA_DIR" source;
assert pkgs.lib.hasInfix "NIXFIED_SERVICE_''\${service_token}_STATE_DIR" source;
assert pkgs.lib.hasInfix "NIXFIED_SERVICE_''\${service_token}_LOG_DIR" source;
assert !(pkgs.lib.hasInfix "runtime_home_override=" source);
assert !(pkgs.lib.hasInfix "runtime_tmp_override=" source);
assert !(pkgs.lib.hasInfix "runtime_xdg_data_override=" source);
assert !(pkgs.lib.hasInfix "runtime_xdg_state_override=" source);
assert !(pkgs.lib.hasInfix "runtime_xdg_cache_override=" source);
assert !(pkgs.lib.hasInfix "\${NIXFIED_RUNTIME_REGISTRY_ROOT:-" source);
assert !(pkgs.lib.hasInfix "\${NIXFIED_RUNTIME_ARTIFACTS_DIR:-" source);
assert !(pkgs.lib.hasInfix "\${NIXFIED_RUNTIME_SERVICE_ROOT:-" source);
assert pkgs.lib.hasInfix "valid_log_level() {" commonSource;
assert pkgs.lib.hasInfix "valid_output_mode() {" commonSource;
pkgs.runCommand "env-sandbox-contract" { } ''
  echo "OK: sandbox contract markers are stable" > "$out"
''
