# Two data formats for the same syntax facts. Neither format emits a scanner.
{ lib, structure }:
checked:
let
  quote = import ./rust-quote.nix { inherit lib; };
  presentation = import ./command-help.nix { inherit lib; };
  rustType =
    argument:
    let
      domain = argument.valueDomain;
    in
    if domain.kind == "Flag" then
      "bool"
    else if domain.kind == "Unsigned" then
      "u${toString domain.bits}"
    else if domain.kind == "Enum" then
      structure.vocabularyMap.${domain.coordinate}.rust.name
    else
      "&str";
  rustInitial =
    argument:
    if argument.initialValue.kind == "Absent" then
      "None"
    else if argument.valueDomain.kind == "Enum" then
      "${rustType argument}::${structure.variant argument.initialValue.value}"
    else
      quote argument.initialValue.value;

in
{
  rust =
    names:
    "// @generated by nix/meta/syntax-project.nix; regenerate with nix run .#regenerate.\n"
    + "const HELP_SHORT: &str = ${quote (builtins.head checked.helpTokens)};\nconst HELP_LONG: &str = ${quote (lib.last checked.helpTokens)};\n"
    + lib.concatMapStrings (
      coordinate:
      let
        vocabulary = structure.vocabularyMap.${coordinate};
        symbols = checked.vocabularySymbols coordinate;
      in
      lib.optionalString
        (lib.any (
          command:
          builtins.elem command.name names
          && lib.any (
            arg: arg.valueDomain.kind == "Enum" && arg.valueDomain.coordinate == coordinate
          ) command.arguments
        ) checked.commands)
        (
          "const ${symbols.choices}: &str = ${quote (presentation.choices vocabulary.members)};\n"
          + lib.concatMapStrings (
            member: "const ${symbols.members.${member}}: &str = ${quote member};\n"
          ) vocabulary.members
        )
    ) checked.enumCoordinates
    + lib.concatMapStrings (
      name:
      let
        symbols = checked.commandSymbols name;
      in
      "const ${symbols.command}: &str = ${quote name};\nconst ${symbols.help}: &str = ${quote checked.help.${name}};\n"
    ) names
    + lib.concatMapStrings (
      entry:
      let
        arg = entry.facts;
        symbols = entry.symbols;
        type = symbols.type or (rustType arg);
      in
      "const ${symbols.token}: &str = ${quote arg.token};\n"
      + lib.optionalString (symbols ? type) "type ${symbols.type} = ${rustType arg};\n"
      + "const ${symbols.initial}: ${
        if arg.initialValue.kind == "Absent" then "Option<${type}>" else type
      } = ${rustInitial arg};\n"
    ) (checked.argumentsFor names);
  shell =
    name:
    let
      command = checked.byName.${name};
    in
    "HELP_SHORT=${lib.escapeShellArg (builtins.head checked.helpTokens)}\nHELP_LONG=${lib.escapeShellArg (lib.last checked.helpTokens)}\n"
    + "${(checked.commandSymbols name).help}=${lib.escapeShellArg checked.help.${name}}\n"
    + lib.concatMapStrings (
      arg:
      let
        initial = arg.initialValue;
        value =
          if initial.kind == "Absent" then
            ""
          else if builtins.isBool initial.value then
            (if initial.value then "1" else "0")
          else
            toString initial.value;
      in
      "${(checked.argumentSymbols command arg).token}=${lib.escapeShellArg arg.token}\n${(checked.argumentSymbols command arg).initial}=${lib.escapeShellArg value}\n"
    ) command.arguments;
}
