{
  lib,
  pkgs,
  system,
}:

let
  authoring = import ../meta/authoring.nix { inherit lib pkgs system; };
  evaluated = authoring.evaluated;
  metadata = authoring.options;
  rendered = pkgs.nixosOptionsDoc {
    options = builtins.removeAttrs evaluated.options [ "_module" ];
    # Declaration paths are evaluator-local store or checkout paths. They add no
    # authoring value and would make the checked reference host-dependent.
    transformOptions = option: option // { declarations = [ ]; };
  };
  header = pkgs.writeText "nixfied-options-header.md" ''
    # Nixfied option reference

    > Generated from the typed modules in `nix/modules/`; do not edit this file
    > by hand. See [DEVELOPMENT.md](DEVELOPMENT.md) for the regeneration command.

    Start with the [adopter guide](GUIDE.md) for workflow and examples. See
    [ADAPTERS.md](ADAPTERS.md) for adapter-specific conventions.

  '';
  combined = pkgs.concatText "nixfied-options-untrimmed.md" [
    header
    rendered.optionsCommonMark
  ];
in
builtins.seq metadata (
  pkgs.runCommand "nixfied-options.md" { } ''
    # Preserve generated formatting while dropping any trailing blank lines.
    awk '
      NF { last = NR }
      { lines[NR] = $0 }
      END { for (line = 1; line <= last; line++) print lines[line] }
    ' ${combined} > "$out"
  ''
)
